AllCops:
  TargetRubyVersion: 3.0.0
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'node_modules/**'
    - 'script/**/*'
    - 'support/**/*'
    - 'tmp/**/*'

# Disable Missing magic comment # frozen_string_literal: true
Style/FrozenStringLiteralComment:
  Enabled: false
# forces single assignment out of if/case statements
Style/ConditionalAssignment:
  Enabled: false
# forces correct use of single vs double quotes
Style/StringLiterals:
  Enabled: false
# forces documentation of classes and modules
Style/Documentation:
  Enabled: false
# forces specific regex syntax
Style/RegexpLiteral:
  Enabled: false
# forces if to be potentialy replaced with guard clause return if
Style/GuardClause:
  Enabled: false
# forces %w notation for array of words
Style/WordArray:
  Enabled: false
# forces %w[] instead of %w()
Style/PercentLiteralDelimiters:
  Enabled: false
# forces maximum on size of methods
Metrics/AbcSize:
  Enabled: false
# forces max complexity of methods
Metrics/CyclomaticComplexity:
  Enabled: false
# forces correct usage of fail vs raise
Style/SignalException:
  Enabled: false
# forces %i[] for an array of symbols
Style/SymbolArray:
  Enabled: false
# forces weird looking syntax on hashes as last argument of method
Layout/FirstHashElementIndentation:
  Enabled: false
# forces weird looking syntax on closing of parenthesis of multi-line methods
Layout/ClosingParenthesisIndentation:
  Enabled: false
# increases the line length to 160 chars
Layout/LineLength:
  Max: 160
# increase the method length to 20 lines
Metrics/MethodLength:
  Max: 30
Metrics/ClassLength:
  Max: 200
Metrics/PerceivedComplexity:
  Max: 10
# Allow extra spaces in arrays
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false
# ActiveAdmin and rake tasks need big blocks
Metrics/BlockLength:
  Exclude:
    - 'app/admin/**/*'
    - 'lib/tasks/**/*'
    - '**/*_spec.rb'
    - 'app/graphql/**/*'
# Allow emojis in Code comments
Style/AsciiComments:
  Enabled: false
# Allow $redis
Style/GlobalVars:
  Enabled: false
# Allow compact syntax for style definitions
Style/ClassAndModuleChildren:
  Enabled: false
# Aligning parameters does not make sense for Strong Params
Layout/ParameterAlignment:
  Enabled: false

Style/NumericLiterals:
  Enabled: false
