default: &defaults
  push_api_key: "<%= Rails.application.credentials.appsignal_push_api_key %>"
  name: "lucien-george-com"
  ignore_errors:
    - ActiveRecord::RecordNotFound
    - ActionController::RoutingError

development:
  <<: *defaults
  active: false

production:
  <<: *defaults
  active: true
