meta_product_name: "Lucien George"
meta_title: "Lucien George - Software Developer"
meta_description: "Lucien George's Portfolio"
meta_image: "cover.png"
twitter_account: "@luciengeorge16"   # required for Twitter Cards
