meta_product_name: "Lucien George"
meta_title: "Software Developer"
meta_description: "Lucien George is a software developer currently working at Shopify"
meta_image: "cover.png"
twitter_account: "@luciengeorge16"   # required for Twitter Cards
